### ISSUE TITLE
Find a suitable visualization package for the web

### ISSUE THREAD

**Issue by jkayani** [ProducthuntAnalytics/data-challenge#1]

**Comment by ssmirr** [comment]
https://www.npmjs.com/package/d3

**Comment by jkayani** [comment]
D3 looks kinda complicated to be honest since it doesn't have any built in charts - you have to draw them all yourself via HTML, CSS, SVG, etc. Could we consider using this instead: https://google-developers.appspot.com/chart/interactive/docs/gallery/columnchart#labeling-columns. Probably not nearly as powerful, but maybe powerful enough.
